### PR TITLE
issue#18 added json logging

### LINKED ISSUE #18: JSON logging for the dispatcher please
This might be a good package to look at https://pypi.org/project/python-json-logger/

### PR DESCRIPTION
**Pull request by timberhill**
- Added json logging using [`structlog` package](https://www.structlog.org/en/stable/why.html)
- Moved logging setup into its own class & file
- Moved config handling to its own class & file
- Updated Dispatcher class to just use the Config class instead of pulling values out of a dict as before
- Updated tests to use the new config class and updated references - no functional changes, just updated the fields that are referenced within objects (e.g. `dispatcher.subreddits` -> `dispatcher.config.subreddits`)

### Additional changes
- Moved the pip install before the app files copy in the dockerfile to speed up the builds via caching
- Bugfix in Makefile + suppress the `Entering directory` messages when running `make test`

Closes #18

### CODE REVIEW

**Comment by timberhill** [comment]
@danyloid the thing with conflicting beta version has happened as you predicted :D

**Comment by danyloid** [comment]
@timberhill let's create issues update pipelines for dispatcher & comments service, shall we ?

I can pick them up next week, if no one beats me to it.

**Comment by timberhill** [comment]
Tested in dev-stack, seems to be working 👍

**Review by fratcliffe — APPROVED** [review]
Tested, works beautifully 😄 
```
2023-05-27 07:52:58 {"event": "Setting up reddit instance", "level": "info", "timestamp": "2023-05-27T06:52:58.407010Z"}
2023-05-27 07:52:58 {"event": "Setting up the dispatcher", "level": "info", "timestamp": "2023-05-27T06:52:58.594963Z"}
2023-05-27 07:52:58 {"event": "Started reddit dispatcher", "level": "info", "timestamp": "2023-05-27T06:52:58.595080Z"}
2023-05-27 07:52:58 {"event": "Getting the subreddit object: all", "level": "info", "timestamp": "2023-05-27T06:52:58.595144Z"}
```

**Pull request merged**
